plugins {
    id 'java'
    id("io.qameta.allure") version "3.0.0"
}

group = 'org.example'
version = '1.0-SNAPSHOT'

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'com.codeborne:selenide:7.10.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testImplementation 'org.assertj:assertj-core:3.27.4'
    testImplementation 'io.qameta.allure:allure-junit5:2.24.0'
    testImplementation 'io.qameta.allure:allure-selenide:2.24.0'
    testImplementation 'io.github.bonigarcia:webdrivermanager:5.8.0'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat "full"
    }
    
    systemProperties += [
            'junit.jupiter.execution.parallel.enabled'                 : true,
            'junit.jupiter.execution.parallel.mode.default'            : 'concurrent',
            'junit.jupiter.execution.parallel.mode.classes.default'    : 'concurrent',
            'junit.jupiter.execution.parallel.config.strategy'         : 'fixed',
            'junit.jupiter.execution.parallel.config.fixed.parallelism': System.getProperty('parallel.threads', '4')
    ]
    
    if (project.hasProperty('tag')) {
        useJUnitPlatform {
            includeTags project.property('tag')
        }
    }
}

allure {
    version = "2.24.0"
    report {
        reportDir = file("build/reports/allure-report")
    }
    results {
        resultsDir = file("build/allure-results")
    }
}